/**
 * types 命名规范
 * 1. 使用常量并全部大写
 * 2. 模块命名使用以下形式命名：主模块约定缩写_操作命名_子模块名称
 */

// 全局
export const HEADER_SET_BOTTOMLINE = 'HEADER_SET_BOTTOMLINE'
export const HEADER_SET_INFOSHOW = 'HEADER_SET_INFOSHOW'
export const HEADER_SET_USERINFO = 'HEADER_SET_USERINFO'

// 登录弹框
export const LOGIN_SET_LOGINWINDOW = 'LOGIN_SET_LOGINWINDOW'

// 用户注册
export const REGISTERED_SET_REGISTERED = 'REGISTERED_SET_REGISTERED'

// 社团动态
export const DYNAMIC_SET_CLUBSEARCH = 'DYNAMIC_SET_CLUBSEARCH'

// 个人信息
export const INFO_SET_INFO = 'INFO_SET_INFO'

// 个人信息弹框
export const USERINFO_SET_USERINFO = 'USERINFO_SET_USERINFO'

// 我的社团
export const MYCLUB_SET_NEWCLUBWINDOW = 'MYCLUB_SET_NEWCLUBWINDOW'
export const MYCLUB_SET_MYCLUB = 'MYCLUB_SET_MYCLUB'

// 社团管理板块

// 基本信息
export const BASICINFO_SET_BASICINFO = 'BASICINFO_SET_BASICINFO'

// 社团成员
export const MEMBERS_SET_MEMBERS = 'MEMBERS_SET_MEMBERS'

// 活动列表
export const ACTIVITY_SET_ACTIVITY = 'ACTIVITY_SET_ACTIVITY'

// 社团架构
export const ARCHITECTURE_SET_ARCHITECTURE = 'ARCHITECTURE_SET_ARCHITECTURE'

// 创建活动
export const NEWACTIVITY_SET_NEWACTIVITY = 'NEWACTIVITY_SET_NEWACTIVITY'
